from __future__ import annotations as _annotations

from dataclasses import dataclass

from . import ModelProfile


@dataclass
class AnthropicModelProfile(ModelProfile):
    """Profile for models used with AnthropicModel.

    ALL FIELDS MUST BE `anthropic_` PREFIXED SO YOU CAN MERGE THEM WITH OTHER MODELS.
    """

    anthropic_max_tokens_limit: int = 1024
    """The maximum number of tokens that can be generated by this model, as documented at https://docs.anthropic.com/en/docs/about-claude/models/overview. Defaults to 1024."""


MAX_TOKENS = {
    'claude-3-haiku': 4096,
    'claude-3-opus': 4096,
    'claude-3-5-haiku': 8192,
    'claude-3-5-sonnet': 8192,
    'claude-3-7-sonnet': 64000,
    'claude-opus-4': 32000,
    'claude-4-opus': 32000,
    'claude-sonnet-4': 64000,
    'claude-4-sonnet': 64000,
}


def anthropic_model_profile(model_name: str) -> ModelProfile | None:
    """Get the model profile for an Anthropic model."""
    max_tokens = 1024
    for model_prefix, model_max_tokens in MAX_TOKENS.items():
        if model_name.startswith(model_prefix):
            max_tokens = model_max_tokens
            break

    return AnthropicModelProfile(anthropic_max_tokens_limit=max_tokens)
