// build dist/prepareEnvCode.js from src/prepare_env.py
const fs = require('fs')
const path = require('path')

const src = path.resolve(__dirname, 'src/prepare_env.py')
const dst = path.resolve(__dirname, 'dist/prepareEnvCode.js')

const pythonCode = fs.readFileSync(src, 'utf8').replace(/\\n/g, '\\\\n')
const jsCode = `// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN "npm run build"
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.preparePythonCode = \`${pythonCode}\`
`

fs.writeFileSync(dst, jsCode, 'utf8')
